export const translation: Record<string, string> = {
	secid: "идентификатор индекса",
	boardid: "идентификатор доски",
	shortname: "название компании",
	prevprice: "предыдущая цена", // цена
	lotsize: "размер лота",
	facevalue: "номинальная стоимость",
	status: "статус",
	boardname: "название доски",
	decimals: "десятичные знаки",
	secname: "название бумаги",
	remarks: "замечания",
	marketcode: "код рынка",
	instrid: "идентификатор инструмента",
	sectorid: "идентификатор сектора",
	minstep: "минимальный шаг",
	prevwaprice: "предыдущая средневзвешенная цена", // цена
	faceunit: "валюта номинала",
	prevdate: "предыдущая дата",
	issuesize: "объем выпуска",
	isin: "международный код ценной бумаги",
	latname: "латинское имя",
	regnumber: "регистрационный номер",
	prevlegalcloseprice: "предыдущая официальная цена закрытия", // цена
	currencyid: "идентификатор валюты",
	sectype: "тип бумаги",
	listlevel: "уровень листинга",
	settledate: "дата расчетов",
	indexid: "идентификатор индекса",
	tradedate: "дата торгов",
	ticker: "тикер",
	shortnames: "название компании",
	secids: "идентификатор бумаги",
	weight: "вес",
	tradingsession: "торговая сессия"
};